import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { prisma } from '../../config/prisma';
import {
  createEmployee,
  createUser,
  currentEmployment,
  resetDb,
  utc,
} from '../../__tests__/helpers/factories';
import { ensureContractRemindersUpToDate } from '../contractReminders';

// There is no scheduler: reminders are generated by an idempotent catch-up run at boot and on
// every HR notification fetch. That makes repeat-safety and per-recipient delivery the two
// properties worth pinning.
beforeEach(async () => {
  await resetDb();
});

afterAll(async () => {
  await prisma.$disconnect();
});

async function remindersFor(userId: number) {
  return prisma.notification.findMany({
    where: { recipientId: userId, type: 'CONTRACT_ENDING' },
  });
}

// Far enough out to be outside any 30-day window, and near enough to be inside one.
const SOON = new Date(Date.now() + 10 * 24 * 60 * 60 * 1000);
const FAR = new Date(Date.now() + 200 * 24 * 60 * 60 * 1000);

describe('ensureContractRemindersUpToDate', () => {
  it('warns HR about a contract inside the window and ignores one outside it', async () => {
    const hr = await createUser({ roleName: 'HR' });
    await createEmployee({ fullName: 'Ending Soon', contractEndDate: SOON });
    await createEmployee({ fullName: 'Ending Later', contractEndDate: FAR });

    await ensureContractRemindersUpToDate();

    const rows = await remindersFor(hr.id);
    expect(rows).toHaveLength(1);
    expect((rows[0].payload as { employeeName: string }).employeeName).toBe('Ending Soon');
  });

  it('is idempotent across repeated runs', async () => {
    const hr = await createUser({ roleName: 'HR' });
    await createEmployee({ contractEndDate: SOON });

    await ensureContractRemindersUpToDate();
    await ensureContractRemindersUpToDate();
    await ensureContractRemindersUpToDate();

    await expect(remindersFor(hr.id)).resolves.toHaveLength(1);
  });

  it('delivers standing reminders to an HR account created afterwards', async () => {
    // Keying idempotency on the employment alone meant the first HR user "used up" the
    // reminder: an account created later was never sent it, and so saw no expiring contract
    // at all until the next one came due.
    const first = await createUser({ roleName: 'HR', email: 'hr1@example.test' });
    await createEmployee({ contractEndDate: SOON });
    await ensureContractRemindersUpToDate();

    const second = await createUser({ roleName: 'HR', email: 'hr2@example.test' });
    await ensureContractRemindersUpToDate();

    await expect(remindersFor(first.id)).resolves.toHaveLength(1);
    await expect(remindersFor(second.id)).resolves.toHaveLength(1);
  });

  it('re-arms when the contract is extended', async () => {
    const hr = await createUser({ roleName: 'HR' });
    const employee = await createEmployee({ contractEndDate: SOON });
    await ensureContractRemindersUpToDate();

    // HR renews: a new end date is a new question, so the warning fires again.
    const employment = await currentEmployment(employee.id);
    const extended = new Date(Date.now() + 20 * 24 * 60 * 60 * 1000);
    await prisma.employment.update({
      where: { id: employment.id },
      data: { contractEndDate: extended },
    });

    await ensureContractRemindersUpToDate();

    await expect(remindersFor(hr.id)).resolves.toHaveLength(2);
  });

  it('includes a contract that already lapsed', async () => {
    // More urgent than one about to expire, not less.
    const hr = await createUser({ roleName: 'HR' });
    await createEmployee({ contractEndDate: utc('2020-01-01') });

    await ensureContractRemindersUpToDate();

    const rows = await remindersFor(hr.id);
    expect(rows).toHaveLength(1);
    expect((rows[0].payload as { daysRemaining: number }).daysRemaining).toBeLessThan(0);
  });

  it('does not warn about somebody already serving notice', async () => {
    // They are leaving; there is no contract to renew.
    const hr = await createUser({ roleName: 'HR' });
    await createEmployee({
      contractEndDate: SOON,
      terminated: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    });

    await ensureContractRemindersUpToDate();

    await expect(remindersFor(hr.id)).resolves.toHaveLength(0);
  });

  it('writes nothing when there is no active HR account', async () => {
    await createUser({ roleName: 'EMPLOYEE' });
    await createEmployee({ contractEndDate: SOON });

    await expect(ensureContractRemindersUpToDate()).resolves.toBe(0);
    await expect(prisma.notification.count()).resolves.toBe(0);
  });

  it('does not duplicate when two callers overlap', async () => {
    // Boot and an HR fetch can coincide. The advisory lock serializes them.
    const hr = await createUser({ roleName: 'HR' });
    await createEmployee({ contractEndDate: SOON });

    await Promise.all([
      ensureContractRemindersUpToDate(),
      ensureContractRemindersUpToDate(),
      ensureContractRemindersUpToDate(),
    ]);

    await expect(remindersFor(hr.id)).resolves.toHaveLength(1);
  });
});
